(ns problem1
  "Each new term in the Fibonacci sequence is generated by adding the previous two terms.
  By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
  find the sum of the even-valued terms.")


;; Solution using `iterate`
;; Generate pairs of successive terms with `f`, then use `map` to extract the first values of each pair
;; to produce a lazy sequence of terms

(defn f [[a b]] [b (+ a b)])

(defn fibonacci-seq []
  (map first (iterate f [1 2])))


(->> (fibonacci-seq)
     (filter even?)
     (take-while #(< % 4000000))
     (apply +))





